[package]
name = "integrity_as_dep"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
# integrity = { git = "https://github.com/fmkra/integrity.git", rev = "6dfa6264ed87a4cece6a4f0538d5b99c0c564140" }
integrity = { path = "../integrity" }

[dev-dependencies]
cairo_test = "2.8.4"
